import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../styles/globals.css";
import RootProvider from "@/providers";

export const metadata: Metadata = {
  title: "CAMPING",
  description: "Generated by create next app",
};

const lato = Lato({
  subsets: ["latin"],
  weight: ["700", "400"],
  variable: "--font-lato",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  function some(name: string) {
    console.log(name);
  }
  return (
    <html lang="en">
      <body className={`${(lato.className, lato.variable)} antialiased`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
